<<<<<<< HEAD
package _16_Exception_Handling;

public class Try_Finally {
    public static void main(String[] args) {

        // try-finally without catch block
        try {
            System.out.println("Inside try block");
            throw new RuntimeException("Test");
        } finally {
            System.out.println("Finally block executed.");
        }
    }
}
=======
package _16_Exception_Handling;

public class Try_Finally {
    public static void main(String[] args) {

        // try-finally without catch block
        try {
            System.out.println("Inside try block");
            throw new RuntimeException("Test");
        } finally {
            System.out.println("Finally block executed.");
        }
    }
}
>>>>>>> 35387576b9a0b809457b398be6486ca5e6dbc9f1
